name: C/C++ CI

on:
  push:
    branches: [ "feature/#2-github-action" ]
  pull_request:
    branches: [ "feature/#2-github-action" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure CMake 
      run: cmake --preset x64 .
    - name: Run Make
      run: |
        cd  /home/runner/work/cpp-action/cpp-action/out/build/x64
        make

    - name: Run Main

      run: |
        cd  /home/runner/work/cpp-action/cpp-action/out/install/x64
        ./myproject
