name: C/C++ CI

on:
  push:
    branches: [ "feature/#2-github-action" ]
  pull_request:
    branches: [ "feature/#2-github-action" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure CMake 
      run: |
        cd myproject
        cmake .
    - name: Run Make
      run: |
        cd myproject
        make
    - name: Run Main
      run: |
        cd myproject
        ./myproject
