name: Swagger Documentation CI

on:
  push:
    branches: [ "feature/#3-swagger-ui" ]
  pull_request:
    branches: [ "feature/#3-swagger-ui" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Generate Swagger UI
      uses: Legion2/swagger-ui-action@v1
      with:
        output: swagger-ui
        spec-file: swagger.yml
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: swagger-ui/index.html
    #- name: Download artifacts
    #  uses: actions/download-artifact@v4
    #  with:
    #    name: swagger-ui
