name: Swagger Documentation CI

on:
  push:
    branches: [ "feature/#3-swagger-ui" ]
  pull_request:
    branches: [ "feature/#3-swagger-ui" ]

jobs:
  generate-openapi-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload swagger.yml
        uses: actions/upload-artifact@v4
        with:
          name: spec-file
          path: swagger.yml
  deploy:
    needs: generate-openapi-spec
    runs-on: ubuntu-latest
    steps:
      - name: Download swagger.yml
        uses: actions/download-artifact@v4
        with:
          name: spec-file
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: swagger.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./swagger-ui
          publish_branch: gh-pages
